name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag appgus.azurecr.io/network-monitor:1.0.0
    - name: Check image was created
      run: docker image ls
    - name: Login to Azure Container Registry
      run: docker login appgus.azurecr.io --username appgus --password ${{ secrets.ACR_PASSWORD }}
    - name: Check if logged in successfully
      run: docker image ls
    - name: Push Image to Azure Container Registry
      run: docker push appgus.azurecr.io/network-monitor:1.0.0
    - name: Install Azure CLI
      run: sudo curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
    - name: Check Azure CLI is installed
      run: az --version
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 
    - run: |
        az webapp list --query "[?state=='Running']"
    - name: Install AKS CLI
      run: az aks install-cli
    - name: Get credentials for AKS Cluster
      run: az aks get-credentials --resource-group automation --name APPAKSDEV01
    - name: List nodes
      run: kubectl get nodes


