name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag network-monitor:1.0.0
    - name: Check image was created
      run: docker image ls
    - name: Login to Docker Hub
      run: docker login -u guxvega -p 388a4aaa-d5e2-4118-bf0a-6d552df62616
    - name: Check if logged in successfully
      run: docker image ls
    - name: Push Image to Docker Hub
      run: docker push network-monitor:1.0.0

