name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag network-monitor:1.0.0
    - name: Check image was created
      run: docker image ls
    - name: Login to Azure Container Registry
      run: docker login appgus.azurecr.io --username appgus --password xIgsFpfaY/2uNIt5nN46nZCWujUm341S
    - name: Check if logged in successfully
      run: docker image ls
    - name: Push Image to Azure Container Registry
      run: docker push appgus.azurecr.io/network-monitor

